version: 2
jobs:
  build_and_deploy:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./mvnw verify -Dspring.profiles.active=test
      - run:
          name: Generate surefire report
          command: ./mvnw surefire-report:report-only
      - run:
          name: Generate failsafe report
          command: ./mvnw surefire-report:failsafe-report-only
      - store_artifacts:
          path: ~/app/target/failsafe-reports/
      - store_artifacts:
          path: ~/app/target/surefire-reports/
      - store_artifacts:
          path: ~/app/target/site/
      - run:
          name: Delete old jar
          command: 'ssh -o StrictHostKeyChecking=no -t external@vps778858.ovh.net ''echo y | rm /app/lunchroom-0.0.1-SNAPSHOT.jar'''
      - run:
          name: Copy new jar
          command: 'scp ~/app/target/lunchroom-0.0.1-SNAPSHOT.jar external@vps778858.ovh.net:/app/'
      - run:
          name: Deploy new applcation
          command: 'ssh -o StrictHostKeyChecking=no external@vps778858.ovh.net ''screen -dmS tomcat_lunchroom sh /usr/local/bin/deploy.sh'''

workflows:
  version: 2
  workflow:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
